Ilk_Mvc_Projesi/Models/Shipper.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Ilk_Mvc_Projesi.Models
{
    public partial class Shipper
    {
        public Shipper()
        {
            Orders = new HashSet<Order>();
        }

        public int ShipperId { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}

Ilk_Mvc_Projesi/ViewModels/ShipperViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ilk_Mvc_Projesi.ViewModels
{
    public class ShipperViewModel
    {
        public int ShipperID { get; set; }
        [Required(ErrorMessage = "Firma Adı alanı gereklidir")]
        [StringLength(15, ErrorMessage = "Firma Adı alanı en fazla 15 karakter olabilir")]
        [Display(Name = "Firma Adı")]
        public string CompanyName { get; set; }
        [Display(Name = "Teelefon Numarası")]
        public string Phone { get; set; }
    }
}

Ilk_Mvc_Projesi/Controllers/ShipperController.cs
using Ilk_Mvc_Projesi.Models;
using Ilk_Mvc_Projesi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ilk_Mvc_Projesi.Controllers
{
    public class ShipperController : Controller
    {
        private readonly NorthwindContext _context;

        public ShipperController(NorthwindContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Shippers
                .Include(x => x.Orders)
                .OrderBy(x => x.CompanyName)
                .ToList();

            return View(data);
        }

        public IActionResult Detail(int? id)
        {
            var category = _context.Shippers
                .Include(x => x.Orders)
                .FirstOrDefault(x => x.ShipperId == id);

            if (category == null)
                return RedirectToAction(nameof(Index));
            return View(category);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ShipperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var shipper = new Shipper()
            {
                CompanyName = model.CompanyName,
                Phone = model.Phone
            };
            _context.Shippers.Add(shipper);
            try
            {
                _context.SaveChanges();
                return RedirectToAction("Detail", new { id = shipper.CompanyName });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"{model.CompanyName} eklenirken bir hata oluştu. Tekrar deneyiniz");
                return View(model);
            }
        }
        public IActionResult Delete(int? shipperId)
        {
            var silinecek = _context.Shippers.FirstOrDefault(s => s.ShipperId == shipperId);
            try
            {
                _context.Shippers.Remove(silinecek);
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Detail), new { id = shipperId });
            }

            TempData["silinen_firma"] = silinecek.CompanyName;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int? id)
        {
            var shipper = _context.Shippers.FirstOrDefault(x => x.ShipperId == id);
            if (shipper == null) return RedirectToAction(nameof(Index));

            var model = new ShipperViewModel()
            {
                ShipperID = shipper.ShipperId,
                CompanyName = shipper.CompanyName,
                Phone = shipper.Phone
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult Update(ShipperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var shipper = _context.Shippers.FirstOrDefault(x => x.ShipperId == model.ShipperID);

            try
            {
                shipper.CompanyName = model.CompanyName;
                shipper.Phone = model.Phone;

                _context.Shippers.Update(shipper);

                _context.SaveChanges();
                return RedirectToAction("Detail", new { id = shipper.ShipperId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"{model.CompanyName} güncellenirken bir hata oluştu. Tekrar deneyiniz");
                return View(model);
            }
        }
    }
}

Ilk_Mvc_Projesi/Views/Shipper/Create.cshtml
@model ShipperViewModel
<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>
<form method="post" asp-action="Create" asp-controller="Shipper">
    <label asp-for="CompanyName"></label>
    <input asp-for="CompanyName" />
    <span class="text-danger" asp-validation-for="CompanyName"></span>
    <br />
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span><br />
    <input type="submit" value="Ekle" class="btn btn-warning" />
</form>

Ilk_Mvc_Projesi/Views/Shipper/Detail.cshtml
@model Shipper

<h1>@Model.CompanyName</h1>
<h3>@Model.Phone</h3>
<a asp-action="Delete" asp-controller="Shipper" asp-route-shipperId=@Model.ShipperId class="btn btn-danger">Firmayı Sil</a>
<a asp-action="Update" asp-controller="Shipper" asp-route-Id=@Model.ShipperId class="btn btn-dark">Firmayı Güncelle</a>

<div class="row">
    <div class="col-9">
        <table class="table-bordered">
            <thead>
                <tr>
                    @*<th>Müşteri</th>
                    <th>Çalışan</th>*@
                    <th>Nakliye</th>
                    <th>Sipariş Tarihi</th>
                    <th>İstenen Tarih</th>
                    <th>Kargo Adresi</th>
                    <th>Kargo Şehri</th>
                    <th>Kargo Ülkesi</th>
                    <th>Gemi Adı</th>
                    <th>Kargo Tarihi</th>
                    <th>Posta Kodu</th>
                    <th>Kargo Bölgesi</th>
                    <th>Kargo Aracı</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Orders)
                {
    <tr>
        @*<td>@item.Customer</td>
        <td>@item.Employee</td>*@
        <td>@item.Freight</td>
        <td>@item.OrderDate</td>
        <td>@item.RequiredDate</td>
        <td>@item.ShipAddress</td>
        <td>@item.ShipCity</td>
        <td>@item.ShipCountry</td>
        <td>@item.ShipName</td>
        <td>@item.ShippedDate</td>
        <td>@item.ShipPostalCode</td>
        <td>@item.ShipRegion</td>
        <td>@item.ShipVia</td>

    </tr>
}
            </tbody>
        </table>
    </div>
</div>

Ilk_Mvc_Projesi/Views/Shipper/Index.cshtml
@model List<Shipper>
@{ var silinenMesaj = @TempData["silinen_firma"]?.ToString(); }
@if (!string.IsNullOrEmpty(silinenMesaj))
{
<h3 class="text-danger">@silinenMesaj isimli firma silinmiştir</h3>}
<p>Toplam Kayıt:@Model.Count</p>
<a asp-action="Create" asp-controller="Shipper" class="btn btn-info">Yeni Firma</a>

<div class="row">
    <div class="col-9">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>Şirket Adı</th>
                    <th>Telefon Numarası</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>@item.CompanyName</td>
        <td>@item.Phone</td>
        <td>
            <a class="btn btn-block btn-info"
               asp-controller="Shipper" asp-action="Detail" asp-route-id="@item.ShipperId">
                Detay
            </a>
        </td>
    </tr>}
            </tbody>
        </table>
    </div>
</div>

Ilk_Mvc_Projesi/Views/Shipper/Update.cshtml
@model ShipperViewModel
<div class="text-danger">
    <div asp-validation-summary="All"></div>
</div>
<form method="post" asp-action="Update" asp-controller="Shipper">
    <input asp-for="ShipperID" type="hidden" />
    <label asp-for="CompanyName"></label>
    <input asp-for="CompanyName" />
    <span class="text-danger" asp-validation-for="CompanyName"></span>
    <br />
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span><br />
    <input type="submit" value="Güncelle" class="btn btn-success" />
</form>